name: 'Lock Threads'

on:
  discussion:
    types: [created, edited, answered]

permissions:
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: lock-threads

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5
        with:
          discussion-inactive-days: '-1'
